name: Main full build (push, weekly)

on:
  push:
    branches: [ "main" ]
  schedule:
    # build weekly to keep buildability
    # delay 20 minutes to avoid resource congestion for GitHub runners
    - cron: "20 0 * * 0"

env:
  CARGO_TERM_COLOR: always
  CARGO_COMMON_ARGUMENTS: --verbose --future-incompat-report --workspace --all-targets

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Format check
      run: cargo fmt -- --verbose --check
    - name: Static analysis
      run: cargo clippy
  test-dev:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build ${CARGO_COMMON_ARGUMENTS}
    - name: Test
      run: cargo test ${CARGO_COMMON_ARGUMENTS}
  test-release:
    needs: check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r ${CARGO_COMMON_ARGUMENTS}
    - name: Test
      run: cargo test -r ${CARGO_COMMON_ARGUMENTS}
